outgoing:
  example:
    webhook: 'https://hooks.slack.com/services/'
    channel: 'general'
    unfurlLinks: true
    format: '{0} has joined the game!'
    event: 'chat'
    filters:
      world:
        blacklist: true
        filter: world
