name: Slack
version: 1.4.0
description: Link your server to Slack!
author: CircuitSoft
website: https://circuitsoft.us

main: us.circuitsoft.slack.bukkit.SlackBukkit

permissions:
    slack.hide.command:
        description: Does not post commands you do to Slack.
        default: false
    slack.commands:
        description: Allows you to have access to Slack commands.
    slack.hide.login:
        description: Does not post to Slack when you login.
        default: false
    slack.hide.logout:
        description: Does not post to Slack when you logout.
        default: false
    slack.hide.chat:
        description: Does not post your chats to Slack.
        default: false
commands:
    slack:
        description: Slack commands.
        permission: slack.command
        usage: Do /slack for a list of Slack's commands.